name: Build Home SPA
on:
  pull_request:
    types: [opened, closed, reopened]
  push:
    branches:
      - 'master'
      - 'release'
    paths: [ 'packages/home-spa/**' ]


#defaults:
#  run:
#    working-directory: one-platform

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  buildJob:
    name: build Deployable
    runs-on: ubuntu-latest
    steps:
      - name: build
        env:
          CUSTOM_ENV: ${{GITHUB_ACTION_PATH}}
        #working-directory: ./packages/home-spa
        run: |
          echo "${GITHUB_ACTION_PATH}"
        #working-directory: one-platform
