name: Build Home SPA
on:
  pull_request:
    types: [opened, closed, reopened]
  push:
    branches:
      - 'master'
      - 'release'
    paths: [ 'packages/home-spa/**' ]


#defaults:
#  run:
#    working-directory: one-platform

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
  buildJob:
    name: build Deployable
    runs-on: ubuntu-latest
    steps:
      - name: build
        env:
          CUSTOM_ENV: ""
        #working-directory: ./packages/home-spa
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"

        #working-directory: one-platform
